### ISSUE TITLE
BowTie index

### ISSUE THREAD

**Issue by nuin** [PapenfussLab/socrates#1]
Hi

Which file created by BowTie should be used as index?

Thanks

**Comment by jibsch** [comment]
Hi,
You should use the prefix to all the files (not including the "."), just as you would when specifying "-x" on the command line with Bowtie2. For example, if your index files are called "reference_bt2_index.1.bt2, reference_bt2_index.2.bt2, ... , reference_bt2_index.4.bt2", then you would supply "reference_bt2_index" as argument to Socrates.
Regards,
Jan

**Comment by nuin** [comment]
Thanks.
