### ISSUE TITLE
preprocessing and realignment of bam files

### ISSUE THREAD

**Issue by karthigayini** [PapenfussLab/socrates#3]
Hi 

I am running SOCRATES on canine exome sequenced tumor and normal bam files. I could not find complete example commands or test data set.  I have few questions. 

1. Is it possible to run BAMStratifier for only a set of specified chromosomes? If so can I know the options for it?

2. When I run realignmentBam on *_final_all_sc_*.bam file, i get an error as "Add anchor information into re-alignment BAM file". The usage requires only soft clipped bam and the output file name. Can I know which input file should be used for realignment (*_all_sc, *_anomalous, *_short_sc).

3.  Should I combine the bam files generated for every chromosome from step 1 (preprocessing the bam) into a single bam file to run through rest of the steps?

**Comment by jibsch** [comment]
Hi,
I hope I can help with your query:
1. Yes, the option is called "-region" followed by a region string (";"-separated chromosome names). This option is only available when running the stratifier individually (as you seem to be doing). 
2. This stage of the algorithm expects realigned soft-clips. The full Socrates pipeline will do this for you using Bowtie2, but when running individual steps, this is up to you. See the documentation on this step, as it can be conveniently piped from the aligner to the Socrates module:

> To run this stage together with an aligner, pipe the SAM output straight into the program. For example: Bowtie2 --local -x INDEX -U SCs | java -jar socrates au.edu.wehi.socrates.RealignmentBAM - OUT

Note, that the alignment is to be performed on the ...long_sc..fastq.gz file 
3. The files should be merged automatically if everything goes as it should. 

Let me know if this works out.
Cheers,
Jan

**Comment by karthigayini** [comment]
Hi

Thank you for quick reply. 

1. I am using BAMstratifier with region, as suggested by you and getting the following error. "java -Xmx10g -cp ~/tools/socrates-1.13-jar-with-dependencies.jar au.edu.wehi.socrates.BAMStratifier --region 1;2  -p 98 ...
usage: BAMStratifier [options] alignment_bam
 -b,--base-quality <base-quality>   Minimum average base quality score of
                                    soft clipped sequence [default: 5]
 -h,--help                          print this message
 -k,--keep-duplicate                keep reads with same alignment
                                    position (including mate position for
                                    paired-end data
 -l,--long-sc-len <long-sc-len>     Length threshold of long soft-clip
                                    [default: 25 (bp)]
 -n,--no-all-sc                     do not output *all_sc.bam
 -p,--percent-id <percent-id>       Minimum alignment percent identity to
                                    reference [default: 95 (%)]
 -q,--min-mapq <min-mapq>           Minimum alignments mapq [default: 5]
 -r,--region <region>               Semicolon separated list of
                                    chromosomes to be stratifeid by this
                                    task [default: null (all)]
 -t,--threads <threads>             Number of threads to use [default: 1]
 -v,--verbose                       be verbose of progress
-bash: 2: command not found

The same error is repeated on using "chr2" chromosome2 etc but runs completely fine with just one chromosome number is specified. 

2. I tried piping the bamstratifier command with realignmentBam and used BAM files ( thought realignment BAM need BAM as input) and hence the problem. FASTQ file for just one chromosome works perfectly fine with realignmentBAM.

**Comment by jibsch** [comment]
Hi,
No problem. Hopefully we can sort it all this time:

1. This would just be your shell truncating the command at the ";". I should have specified this. Try 

>     -region "1;2" 

1. (continued) The names or numbers have to match up with what's in the Bam file. 

2. The BAMStratifier produces a file called "...*long_sc_...fastq.gz". This file has to be realigned to the reference genome with Bowtie2, BWA or the like. It does not have to be the same aligner as for the original alignment of the BAM file, but I recommend that. Most importantly, the index has to have the same chromosome names as in the original BAM file, otherwise Socrates won't find anything. Have a look at the command quote from my earlier post for an example of piping the output from Bowtie2 into the RealignmentBAM program.

Please let me know, if this works.
Cheers,
Jan

**Comment by karthigayini** [comment]
Both works perfectly well now. Thanks a lot for the help!

**Comment by jibsch** [comment]
Great.
I close the issue for now, but let me know if you run into anything else.

**Comment by karthigayini** [comment]
Sure. 
I have continued with the other open issue "too many open files" which is the other problem I have. It would be really helpful if you can have a look at it as well.
